// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbPtXY0wIVxam4860CC8Helwi4-RTZ0LE',
    appId: '1:688435362370:web:d8ae68b92a547702a1cbdb',
    messagingSenderId: '688435362370',
    projectId: 'vazi-kali',
    authDomain: 'vazi-kali.firebaseapp.com',
    storageBucket: 'vazi-kali.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX0payI8pvV4XtrYJ3MeSYxhKG5rzQi7g',
    appId: '1:688435362370:android:b07153449cddefa6a1cbdb',
    messagingSenderId: '688435362370',
    projectId: 'vazi-kali',
    storageBucket: 'vazi-kali.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATrtshQWP0EMkYLnkl82Ukc-J9-u_Qw5k',
    appId: '1:688435362370:ios:9e64ee077c0d9188a1cbdb',
    messagingSenderId: '688435362370',
    projectId: 'vazi-kali',
    storageBucket: 'vazi-kali.firebasestorage.app',
    iosBundleId: 'com.example.starFashion',
  );
}
